export const dummy = {
  page: 1,
  results: [
    {
      adult: false,
      backdrop_path: "/Asg2UUwipAdE87MxtJy7SQo08XI.jpg",
      genre_ids: [28, 14, 27],
      id: 957452,
      original_language: "en",
      original_title: "The Crow",
      overview:
        "10월 30일 '악마의 날', 까마귀의 저주로 죽음에서 부활한 에릭(빌 스카스가드)의 잔인한 복수극을 담은 다크 히어로 액션물",
      popularity: 2177.43,
      poster_path: "/58QT4cPJ2u2TqWZkterDq9q4yxQ.jpg",
      release_date: "2024-08-21",
      title: "더 크로우",
      video: false,
      vote_average: 5.434,
      vote_count: 386,
    },
    {
      adult: false,
      backdrop_path: "/9BQqngPfwpeAfK7c2H3cwIFWIVR.jpg",
      genre_ids: [10749, 18],
      id: 1079091,
      original_language: "en",
      original_title: "It Ends with Us",
      overview:
        "아버지의 장례식을 멋지게 망치고 아지트로 향한 ‘릴리’는 어딘가 위태롭지만 매력적인 남자 ‘라일’에게 순식간에 마음을 빼앗긴다. 새로운 도시에서 자신의 이름을 건 꽃집을 오픈한 릴리는 운명처럼 라일을 다시 만나게 되고 걷잡을 수 없는 사랑에 빠져든다. 그러던 어느 날, 어린 시절의 모든 상처를 알고 있는 첫사랑 ‘아틀라스’와 우연히 재회한 후 감당하기 벅찬 라일의 위협적인 모습을 목격하게 되고 완벽했던 관계가 순식간에 요동치면서 릴리는 피할 수 없는 선택의 기로에 서게 되는데… 외면하고 싶지만 마주해야 하는 사랑과 선택의 순간 올가을, 모두에게 위로와 용기를 선사하는 특별한 이야기!",
      popularity: 1979.669,
      poster_path: "/287MYoxjfINSyfaaV636Z2ioR36.jpg",
      release_date: "2024-08-07",
      title: "우리가 끝이야",
      video: false,
      vote_average: 6.876,
      vote_count: 473,
    },
    {
      adult: false,
      backdrop_path: "/yDHYTfA3R0jFYba16jBB1ef8oIt.jpg",
      genre_ids: [28, 35, 878],
      id: 533535,
      original_language: "en",
      original_title: "Deadpool & Wolverine",
      overview:
        "히어로 생활에서 은퇴한 후, 평범한 중고차 딜러로 살아가던 ‘데드풀’이 예상치 못한 거대한 위기를 맞아 모든 면에서 상극인 ‘울버린’을 찾아가게 되며 펼쳐지는 도파민 폭발 액션 블록버스터.",
      popularity: 1833.435,
      poster_path: "/4Zb4Z2HjX1t5zr1qYOTdVoisJKp.jpg",
      release_date: "2024-07-24",
      title: "데드풀과 울버린",
      video: false,
      vote_average: 7.672,
      vote_count: 3121,
    },
    {
      adult: false,
      backdrop_path: "/dKvvW3euRwUY0Nyl6JBP5tXLPJW.jpg",
      genre_ids: [16, 10751, 12, 35, 14, 18],
      id: 1022789,
      original_language: "en",
      original_title: "Inside Out 2",
      overview:
        "13살이 된 라일리의 행복을 위해 매일 바쁘게 머릿속 감정 컨트롤 본부를 운영하는 ‘기쁨’, ‘슬픔’, ‘버럭’, ‘까칠’, ‘소심’. 그러던 어느 날, 낯선 감정인 ‘불안’, ‘당황’, ‘따분’, ‘부럽’이가 본부에 등장하고, 언제나 최악의 상황을 대비하며 제멋대로인 ‘불안’이와 기존 감정들은 계속 충돌한다. 결국 새로운 감정들에 의해 본부에서 쫓겨나게 된 기존 감정들은 다시 본부로 돌아가기 위해 위험천만한 모험을 시작하는데…",
      popularity: 1430.571,
      poster_path: "/x2BHx02jMbvpKjMvbf8XxJkYwHJ.jpg",
      release_date: "2024-06-11",
      title: "인사이드 아웃 2",
      video: false,
      vote_average: 7.638,
      vote_count: 3809,
    },
    {
      adult: false,
      backdrop_path: "/lgkPzcOSnTvjeMnuFzozRO5HHw1.jpg",
      genre_ids: [16, 10751, 35, 28],
      id: 519182,
      original_language: "en",
      original_title: "Despicable Me 4",
      overview:
        "슈트-업 하고 악당 전담 처리반 AVL이 된 에이전트 미니언즈와 미니언즈 만큼 귀여운 그루 주니어가 태어나면서 더욱 완벽해진 그루 패밀리. 이들 앞에 과거 그루의 고등학교 동창이자 그에게 체포당했던 빌런 맥심이 등장하고, 오직 그루를 향한 복수심에 불타올라 탈옥까지 감행한 맥심은 그루 패밀리의 뒤를 바짝 추격하며 위협을 가하기 시작하는데... 과연 에이전트 미니언즈와 그루 패밀리는 맥심을 막아낼 수 있을까?",
      popularity: 1067.022,
      poster_path: "/5hl1PEpAvZ8Ok37kB7woIssHi3X.jpg",
      release_date: "2024-06-20",
      title: "슈퍼배드 4",
      video: false,
      vote_average: 7.162,
      vote_count: 1736,
    },
    {
      adult: false,
      backdrop_path: "/mKOBdgaEFguADkJhfFslY7TYxIh.jpg",
      genre_ids: [28, 878, 35, 12, 53],
      id: 365177,
      original_language: "en",
      original_title: "Borderlands",
      overview: "",
      popularity: 980.083,
      poster_path: "/865DntZzOdX6rLMd405R0nFkLmL.jpg",
      release_date: "2024-08-07",
      title: "보더랜드",
      video: false,
      vote_average: 5.898,
      vote_count: 605,
    },
    {
      adult: false,
      backdrop_path: "/dTaqzXA1auKRUjHPQjR3u0W7Gfl.jpg",
      genre_ids: [9648, 53],
      id: 840705,
      original_language: "en",
      original_title: "Blink Twice",
      overview: "",
      popularity: 945.588,
      poster_path: "/lZGOK0I2DJSRlEPNOAFTSNxSjDD.jpg",
      release_date: "2024-08-21",
      title: "블링크 트와이스",
      video: false,
      vote_average: 6.684,
      vote_count: 396,
    },
    {
      adult: false,
      backdrop_path: "/9oYdz5gDoIl8h67e3ccv3OHtmm2.jpg",
      genre_ids: [18, 27, 878],
      id: 933260,
      original_language: "en",
      original_title: "The Substance",
      overview:
        "더 나은 버전의 당신을 꿈꿔본 적 있나요? 당신의 인생을 바꿔줄 신제품 ‘서브스턴스’. ‘서브스턴스’는 또 다른 당신을 만들어냅니다. 새롭고, 젊고, 더 아름답고, 더 완벽한 당신을. 단 한가지 규칙, 당신의 시간을 공유하면 됩니다. 당신을 위한 일주일, 새로운 당신을 위한 일주일, 각각 7일간의 완벽한 밸런스. 쉽죠? 균형을 존중한다면… 무엇이 잘못될 수 있을까요?",
      popularity: 905.605,
      poster_path: "/bnU26DZMzWWfpGZ9VUAAzSyou1u.jpg",
      release_date: "2024-09-07",
      title: "서브스턴스",
      video: false,
      vote_average: 7.229,
      vote_count: 120,
    },
    {
      adult: false,
      backdrop_path: "/tncbMvfV0V07UZozXdBEq4Wu9HH.jpg",
      genre_ids: [28, 80, 53, 35],
      id: 573435,
      original_language: "en",
      original_title: "Bad Boys: Ride or Die",
      overview:
        "마이애미 강력반 최고의 콤비 마이크와 마커스. 가족 같은 하워드 반장이 사망 전 마약 카르텔 조직의 비리에 연루되었다는 뉴스 속보를 접하게 된다. 하지만 아무도 믿지 말라는 하워드 반장의 비밀 메시지를 받은 마이크와 마커스 형사는 사건의 진실을 밝히기 위해 위험한 수사를 시작한다. 서서히 드러나는 거대한 음모와 마주하게 된 나쁜 녀석들. 그러나 이들 역시 함정에 빠져 사건의 용의자로 지목되며 동료 경찰들은 물론 마약 카르텔 조직에게도 쫓기는 신세가 되고 마는데…",
      popularity: 878.95,
      poster_path: "/wIrhEUBWjRmZuL1Ix41cF2LhJrW.jpg",
      release_date: "2024-06-05",
      title: "나쁜 녀석들: 라이드 오어 다이",
      video: false,
      vote_average: 7.551,
      vote_count: 2039,
    },
    {
      adult: false,
      backdrop_path: "/A1dZ6faTjg0e6HYftBmEKujuXGQ.jpg",
      genre_ids: [35, 14],
      id: 917496,
      original_language: "en",
      original_title: "Beetlejuice Beetlejuice",
      overview:
        "유령과 대화하는 영매로 유명세를 타게 된 리디아와 그런 엄마가 마음에 들지 않는 10대 딸 아스트리드. 할아버지 찰스의 갑작스러운 죽음으로 가족들은 함께 시골 마을에 내려간다. 유령을 보는 엄마가 마음에 들지 않는 아스트리드는 방황하던 중 함정에 빠져 저세상에 발을 들이게 되고 딸을 구하기 위해 리디아는 인간을 믿지 않는 저세상 슈퍼스타 비틀쥬스를 소환한다. 이루지 못한 리디아와의 결혼을 조건으로 내민 비틀쥬스. 이번엔 아스트리드가 비틀쥬스를 다시 저세상으로 보내야 하는데···",
      popularity: 851.969,
      poster_path: "/ypWQatJYyESE5PIzdlSdiOyWYja.jpg",
      release_date: "2024-09-04",
      title: "비틀쥬스 비틀쥬스",
      video: false,
      vote_average: 7.161,
      vote_count: 697,
    },
    {
      adult: false,
      backdrop_path: "/sjC29cgm4qZAnpOJQbYKCxDCcra.jpg",
      genre_ids: [27, 878, 53],
      id: 1062215,
      original_language: "en",
      original_title: "Afraid",
      overview: "",
      popularity: 847.166,
      poster_path: "/gUREuXCnJLVHsvKXDH9fgIcfM6e.jpg",
      release_date: "2024-08-28",
      title: "어프레이드",
      video: false,
      vote_average: 6.409,
      vote_count: 121,
    },
    {
      adult: false,
      backdrop_path: "/wSZbtiFIK1fkKZdSRtn2kz2Ttfd.jpg",
      genre_ids: [28, 35, 80],
      id: 1139817,
      original_language: "ko",
      original_title: "무도실무관",
      overview:
        "힘든 사람을 그냥 지나치지 못하는 무술 유단자 이정도. 보호관찰관 김선민이 그런 정도를 알아보고 ‘무도실무관’을 권한다. 이제 전자발찌 대상자를 감시하며 범죄를 예방하는 그들의 활약이 펼쳐진다.",
      popularity: 778.713,
      poster_path: "/iuwUEZYNOHzhoNoRj6mcXd2xbYr.jpg",
      release_date: "2024-09-10",
      title: "무도실무관",
      video: false,
      vote_average: 7.865,
      vote_count: 126,
    },
    {
      adult: false,
      backdrop_path: "/tAwfoDyKiYa4KQdUp3DTMrEs4En.jpg",
      genre_ids: [16, 878, 12, 10751],
      id: 698687,
      original_language: "en",
      original_title: "Transformers One",
      overview:
        "트랜스포머 시리즈의 주역, 옵티머스 프라임과 메가트론이 한때 형제와도 같은 친구사이였고, 그들이 어떻게 사이버트론 행성의 운명을 바꾸고 영원한 숙적이 되었는지 그 시작에 대한 이야기를 다루고 있다.",
      popularity: 705.499,
      poster_path: "/c2JXlWzvXegSda8qaATr8I47kMx.jpg",
      release_date: "2024-09-11",
      title: "트랜스포머 ONE",
      video: false,
      vote_average: 7.2,
      vote_count: 63,
    },
    {
      adult: false,
      backdrop_path: "/7cDsJInZGnNC1IFQL5kgYsZSXr3.jpg",
      genre_ids: [28, 80, 18],
      id: 1186947,
      original_language: "pt",
      original_title: "Bandida - A Número Um",
      overview:
        "악명높은 브라질 파벨라에서 성장한 젊은 여성이 사랑과 범죄 사이를 헤쳐 나간다. 위험천만한 갱단 간 경쟁과 배신 속에서 권력을 손에 넣기 위해 악착같이 발버둥 치며.",
      popularity: 662.436,
      poster_path: "/x1n3ZFBR7yuWrmts7GRZIcUtTVo.jpg",
      release_date: "2024-06-20",
      title: "밴딧: 넘버 원",
      video: false,
      vote_average: 6.329,
      vote_count: 38,
    },
    {
      adult: false,
      backdrop_path: "/hZVIwxi6kK4KnpVPEWwdhG0cMM5.jpg",
      genre_ids: [9648, 53],
      id: 1012148,
      original_language: "en",
      original_title: "Chapel",
      overview: "",
      popularity: 641.983,
      poster_path: "/94sIggRUBioP19m3vJQfV3lq6Z6.jpg",
      release_date: "2024-01-17",
      title: "Chapel",
      video: false,
      vote_average: 5.875,
      vote_count: 12,
    },
    {
      adult: false,
      backdrop_path: "/blqiNjJefmY10Wx6y2vgJJWljJj.jpg",
      genre_ids: [28, 53],
      id: 949484,
      original_language: "en",
      original_title: "Hounds of War",
      overview: "",
      popularity: 639.86,
      poster_path: "/lRBT73EWsiQPuqK3YS3BnBW0Zwi.jpg",
      release_date: "2024-08-29",
      title: "Hounds of War",
      video: false,
      vote_average: 6.28,
      vote_count: 41,
    },
    {
      adult: false,
      backdrop_path: "/cyKH7pDFlxIXluqRyNoHHEpxSDX.jpg",
      genre_ids: [80, 28, 53, 18],
      id: 646097,
      original_language: "en",
      original_title: "Rebel Ridge",
      overview:
        "작은 도시를 방문한 전직 해병대원. 사촌의 보석 신청에 쓰려던 현금 가방을 관할 경찰에게 부당하게 압수당하자 그곳에 만연한 부패에 정면으로 맞서기로 한다.",
      popularity: 597.208,
      poster_path: "/ltAyMY5j73LtIqTzlFwPlfZb1K.jpg",
      release_date: "2024-08-27",
      title: "레블 리지",
      video: false,
      vote_average: 7.032,
      vote_count: 694,
    },
    {
      adult: false,
      backdrop_path: "/qwK9soQmmJ7kRdjLZVXblw3g7AQ.jpg",
      genre_ids: [28, 12, 53, 80],
      id: 7451,
      original_language: "en",
      original_title: "xXx",
      overview:
        "싸이렌이 온 거리를 울려 퍼지며 요란한 추격씬이 벌어지는 도중 한 녀석이 콜벳를 몰고 다리를 돌진, 200미터 높이에서 자동차 번지를 시도한다. 짜릿한 곡예를 선보인 후 낙하산을 펴고 유유히 사라지는 녀석의 이름은 '젠더 케이지'. 인터넷에 생방송된 이 장면은 전세계 네티즌들에게 열렬한 환호를 받는다. 또 한 번의 멋진 프로젝트로 영웅 대접을 받는 젠더 케이지. 그러나 파티가 무르익을 무렵, 갑자기 들이닥친 특수부대는 그에게 신경 안정제를 쏜 후 잠들게 한다. 깨어난 곳은 알 수 없는 레스토랑. 어리둥절한 그 곳은 갑자기 강도들의 침입장으로 돌변하고, 단숨에 상황을 정리해버린 그에게 기븐스가 축하 인사를 전한다. 미국 비밀첩보국 NSA의 1차 테스트를 통과한 것. 이후 또 다시 잠에서 깨어난 곳은 비행기 안. 2번째 테스트로 콜럼비아 마약 밀매상의 아지트에 던져진 젠더 케이지. 때마침 콜럼비아 정부와 마약상들의 충돌로 아수라장이 된 그곳에서 살아남기 위한 치열한 전쟁이 펼쳐지는데...  상황종료 후 유유히 나타난 기븐스는 NSA의 테스트를 유일하게 통과한 그에게 비밀요원이 되어줄 것을 부탁한다. 단 그렇지 않을 경우는 감옥행뿐이라는 단서를 둔다. 젠더 케이지의 코드명은 트리플 X. 첫번째 임무지는 비밀요원의 무덤이라는 별칭을 가지고 있는 도시 프라하. 이제 얼떨결에 비밀요원이 되어버린 트리플 X의 위험한 여정이 시작되는데.",
      popularity: 592.639,
      poster_path: "/xeEw3eLeSFmJgXZzmF2Efww0q3s.jpg",
      release_date: "2002-08-09",
      title: "트리플 엑스",
      video: false,
      vote_average: 5.935,
      vote_count: 4200,
    },
    {
      adult: false,
      backdrop_path: "/9SSEUrSqhljBMzRe4aBTh17rUaC.jpg",
      genre_ids: [27, 878, 28],
      id: 945961,
      original_language: "en",
      original_title: "Alien: Romulus",
      overview:
        "2142년, 부모 세대가 맞닥뜨렸던 암울한 미래를 피하려는 청년들이 더 나은 삶을 찾기 위해 식민지를 떠날 계획을 세운다. 하지만 버려진 우주 기지 로물루스에 도착한 이들은 악몽과도 같은 에이리언의 무자비한 공격에 쫓기기 시작한다. 그 누구도 그들의 절규를 들을 수 없는 우주 한가운데, 생존을 위한 치열한 사투를 벌여야 하는데...",
      popularity: 554.339,
      poster_path: "/bMGcJVd4hXlDcevRJZBK5qROlyP.jpg",
      release_date: "2024-08-13",
      title: "에이리언: 로물루스",
      video: false,
      vote_average: 7.1,
      vote_count: 1074,
    },
    {
      adult: false,
      backdrop_path: "/1pbV8uC6EUYOYnPqWfrQFPdAj1O.jpg",
      genre_ids: [80, 28, 12, 53, 18],
      id: 1147710,
      original_language: "ko",
      original_title: "하이재킹",
      overview:
        "1971년 겨울 속초공항 여객기 조종사 태인과 규식은 김포행 비행에 나선다. 승무원 옥순의 안내에 따라 탑승 중인 승객들의 분주함도 잠시, 이륙한지 얼마 되지 않아 사제폭탄이 터지며 기내는 아수라장이 된다. 여객기를 통째로 납치하려는 용대는 조종실을 장악하고 무작정 북으로 기수를 돌리라 협박한다. 폭발 충격으로 규식은 한 쪽 시력을 잃고 이제 여객기를 조종할 수 있는 사람은 태인 뿐. 이들은 여객기를 무사히 착륙시키기 위한 사투를 시작하는데...",
      popularity: 553.097,
      poster_path: "/pLEenJ0I1XqySVezRdETf2n2w7H.jpg",
      release_date: "2024-06-21",
      title: "하이재킹",
      video: false,
      vote_average: 6.306,
      vote_count: 31,
    },
  ],
  total_pages: 46220,
  total_results: 924389,
};
